#!/bin/sh

# script/bootstrap: Resolve all dependencies that the application requires to
#                   run.

set -e
set -x
cd "$(dirname "$0")/.."

git submodule init
git submodule update
npm install
bower install
