#!/bin/sh

# script/bootstrap: Resolve all dependencies that the application requires to
#                   run.

set -e
cd "$(dirname "$0")/.."
set -x

git submodule init
git submodule update
npm install
bower install
