#!/bin/sh

# script/setup: Set up application for the first time after cloning, or set it
#               back to the initial first unused state.

# TODO: make database reset possible, too = #563 = create-migrate-wipe-unify

set -e
cd "$(dirname "$0")/.."
set -x

script/bootstrap
./init.coffee --create-database=both --migrate-tables --unify-export --monsters --items --optimize-tables
./init.coffee --info
