#!/bin/sh

# script/test: Run test suite for application. Optionallly pass in a path to an
#              individual test file to run a single test.

# TODO: support running single test

set -e
cd "$(dirname "$0")/.."
set -x

if [ "$1" "==" "--fast" ]; then
	gulp test
else
	gulp
fi
