#!/bin/sh

# script/update: Update application to run for its current checkout.

set -e
cd "$(dirname "$0")/.."
set -x

script/bootstrap
./init.coffee --migrate-tables --unify-export --monsters --items --optimize
./init.coffee --info
